version: '26.1.2'

services:
  db_auth:
    container_name: DBSpring
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - "15336:5432"
    environment:
      - POSTGRES_PASSWORD=toor36547
      - POSTGRES_USER=admin
      - POSTGRES_DB=bookstore
    image: postgres:12.19-alpine3.19